import { AvatarStyle, NoseType, MouthType, EyeType, EyebrowType, SkinColor, AccessoriesType, FacialHairType, HairColor, TopType, ClotheType, BackgroundColor, ClotheColor, GraphicType, PetType, AwardType, HatColor, AccessoriesColor } from '../options';
export declare class CustomAvatarBaseComponent {
    private _backColor;
    private _backgroundColor;
    private _skinColor;
    private _color;
    width: number;
    widthFull: boolean;
    height: number;
    transform: string;
    viewBox: string;
    noFeatures: boolean;
    noPet: boolean;
    noAward: boolean;
    avatarStyle: AvatarStyle;
    svgClass: string;
    backgroundColor: BackgroundColor;
    readonly backColor: string;
    clotheType: ClotheType;
    graphicType: GraphicType;
    clotheColor: ClotheColor;
    clotheColor2: ClotheColor;
    clotheColor3: ClotheColor;
    topType: TopType;
    skinColor: SkinColor;
    readonly color: string;
    noseType: NoseType;
    mouthType: MouthType;
    eyeType: EyeType;
    eyebrowType: EyebrowType;
    eyebrowColor: HairColor;
    accessoriesType: AccessoriesType;
    facialHairType: FacialHairType;
    facialHairColor: HairColor;
    hairColor: HairColor;
    petType: PetType;
    readonly petTypeVisible: boolean;
    awardType: AwardType;
    readonly awardTypeVisible: boolean;
    hatColor: HatColor;
    accessoriesColor: AccessoriesColor;
    mask1: string;
    mask2: string;
    mask3: string;
    path1: string;
    path3: string;
    path5: string;
    urlFix(path: string): string;
}
